#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v3
# autospec commit: c1050fe
#
Name     : dosfstools
Version  : 4.2
Release  : 23
URL      : https://github.com/dosfstools/dosfstools/archive/v4.2/dosfstools-4.2.tar.gz
Source0  : https://github.com/dosfstools/dosfstools/archive/v4.2/dosfstools-4.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: dosfstools-bin = %{version}-%{release}
Requires: dosfstools-license = %{version}-%{release}
Requires: dosfstools-man = %{version}-%{release}
BuildRequires : systemd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
dosfstools consists of the programs mkfs.fat, fsck.fat and fatlabel to create,
check and label file systems of the FAT family.  The dosfstools are licensed
under the GNU GPL version 3 or later. See the file COPYING for details.

%package bin
Summary: bin components for the dosfstools package.
Group: Binaries
Requires: dosfstools-license = %{version}-%{release}

%description bin
bin components for the dosfstools package.


%package doc
Summary: doc components for the dosfstools package.
Group: Documentation
Requires: dosfstools-man = %{version}-%{release}

%description doc
doc components for the dosfstools package.


%package license
Summary: license components for the dosfstools package.
Group: Default

%description license
license components for the dosfstools package.


%package man
Summary: man components for the dosfstools package.
Group: Default

%description man
man components for the dosfstools package.


%prep
%setup -q -n dosfstools-4.2
cd %{_builddir}/dosfstools-4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701950396
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%autogen --disable-static --enable-compat-symlinks
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701950396
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dosfstools
cp %{_builddir}/dosfstools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/dosfstools/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dosfsck
/usr/bin/dosfslabel
/usr/bin/fatlabel
/usr/bin/fsck.fat
/usr/bin/fsck.msdos
/usr/bin/fsck.vfat
/usr/bin/mkdosfs
/usr/bin/mkfs.fat
/usr/bin/mkfs.msdos
/usr/bin/mkfs.vfat

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/dosfstools/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dosfstools/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/dosfsck.8
/usr/share/man/man8/dosfslabel.8
/usr/share/man/man8/fatlabel.8
/usr/share/man/man8/fsck.fat.8
/usr/share/man/man8/fsck.msdos.8
/usr/share/man/man8/fsck.vfat.8
/usr/share/man/man8/mkdosfs.8
/usr/share/man/man8/mkfs.fat.8
/usr/share/man/man8/mkfs.msdos.8
/usr/share/man/man8/mkfs.vfat.8
